#
# Copyright 2023. Clumio, A Commvault Company.
#

from typing import Any, Dict, Mapping, Optional, Sequence, Type, TypeVar

from clumioapi.models import delete_rule_response_links as delete_rule_response_links_

T = TypeVar('T', bound='DeleteRuleResponse')


class DeleteRuleResponse:
    """Implementation of the 'DeleteRuleResponse' model.

    Attributes:
        links:
            URLs to pages related to the resource.
        preview_id:
            The Clumio-assigned ID of the preview generated by this request. Only valid if
            `execution_type` is set to `dryrun`.
        task_id:
            The Clumio-assigned ID of the task generated by this request.
    """

    # Create a mapping from Model property names to API property names
    _names: dict[str, str] = {'links': '_links', 'preview_id': 'preview_id', 'task_id': 'task_id'}

    def __init__(
        self,
        links: delete_rule_response_links_.DeleteRuleResponseLinks | None = None,
        preview_id: str | None = None,
        task_id: str | None = None,
    ) -> None:
        """Constructor for the DeleteRuleResponse class."""

        # Initialize members of the class
        self.links: delete_rule_response_links_.DeleteRuleResponseLinks | None = links
        self.preview_id: str | None = preview_id
        self.task_id: str | None = task_id

    @classmethod
    def from_dictionary(cls: Type[T], dictionary: Mapping[str, Any]) -> T:
        """Creates an instance of this model from a dictionary

        Args:
            dictionary: A dictionary representation of the object as obtained
                from the deserialization of the server's response. The keys
                MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.
        """

        dictionary = dictionary or {}
        # Extract variables from the dictionary
        val = dictionary.get('_links', None)
        val_links = delete_rule_response_links_.DeleteRuleResponseLinks.from_dictionary(val)

        val = dictionary.get('preview_id', None)
        val_preview_id = val

        val = dictionary.get('task_id', None)
        val_task_id = val

        # Return an object of this model
        return cls(
            val_links,
            val_preview_id,
            val_task_id,
        )
