#
# Copyright 2023. Clumio, Inc.
#

from typing import Any, Dict, Mapping, Optional, Sequence, Type, TypeVar

from clumioapi.models import set_assignments_response_links

T = TypeVar('T', bound='SetAssignmentsResponse')


class SetAssignmentsResponse:
    """Implementation of the 'SetAssignmentsResponse' model.

    Attributes:
        links:
            URLs to pages related to the resource.
        task_id:
            The Clumio-assigned ID of the task generated by this request.
    """

    # Create a mapping from Model property names to API property names
    _names = {'links': '_links', 'task_id': 'task_id'}

    def __init__(
        self,
        links: set_assignments_response_links.SetAssignmentsResponseLinks = None,
        task_id: str = None,
    ) -> None:
        """Constructor for the SetAssignmentsResponse class."""

        # Initialize members of the class
        self.links: set_assignments_response_links.SetAssignmentsResponseLinks = links
        self.task_id: str = task_id

    @classmethod
    def from_dictionary(cls: Type, dictionary: Mapping[str, Any]) -> Optional[T]:
        """Creates an instance of this model from a dictionary

        Args:
            dictionary: A dictionary representation of the object as obtained
                from the deserialization of the server's response. The keys
                MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.
        """
        if not dictionary:
            return None

        # Extract variables from the dictionary
        key = '_links'
        links = (
            set_assignments_response_links.SetAssignmentsResponseLinks.from_dictionary(
                dictionary.get(key)
            )
            if dictionary.get(key)
            else None
        )

        task_id = dictionary.get('task_id')
        # Return an object of this model
        return cls(links, task_id)
