#
# Copyright 2023. Clumio, A Commvault Company.
#

from typing import Any, Dict, Mapping, Optional, Sequence, Type, TypeVar

from clumioapi.models import rule as rule_
from clumioapi.models import update_rule_response_links as update_rule_response_links_

T = TypeVar('T', bound='UpdateRuleResponse')


class UpdateRuleResponse:
    """Implementation of the 'UpdateRuleResponse' model.

    Attributes:
        links:
            URLs to pages related to the resource.
        rule:
            A rule applies an action subject to a condition criteria.
        task_id:
            The Clumio-assigned ID of the task generated by this request.
    """

    # Create a mapping from Model property names to API property names
    _names: dict[str, str] = {'links': '_links', 'rule': 'rule', 'task_id': 'task_id'}

    def __init__(
        self,
        links: update_rule_response_links_.UpdateRuleResponseLinks | None = None,
        rule: rule_.Rule | None = None,
        task_id: str | None = None,
    ) -> None:
        """Constructor for the UpdateRuleResponse class."""

        # Initialize members of the class
        self.links: update_rule_response_links_.UpdateRuleResponseLinks | None = links
        self.rule: rule_.Rule | None = rule
        self.task_id: str | None = task_id

    @classmethod
    def from_dictionary(cls: Type[T], dictionary: Mapping[str, Any]) -> T:
        """Creates an instance of this model from a dictionary

        Args:
            dictionary: A dictionary representation of the object as obtained
                from the deserialization of the server's response. The keys
                MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.
        """

        dictionary = dictionary or {}
        # Extract variables from the dictionary
        val = dictionary.get('_links', None)
        val_links = update_rule_response_links_.UpdateRuleResponseLinks.from_dictionary(val)

        val = dictionary.get('rule', None)
        val_rule = rule_.Rule.from_dictionary(val)

        val = dictionary.get('task_id', None)
        val_task_id = val

        # Return an object of this model
        return cls(
            val_links,
            val_rule,
            val_task_id,
        )
