#
# Copyright 2023. Clumio, A Commvault Company.
#

from typing import Any, Dict, Mapping, Optional, Sequence, Type, TypeVar

from clumioapi.models import policy_embedded as policy_embedded_
from clumioapi.models import policy_operation as policy_operation_
from clumioapi.models import update_policy_response_links as update_policy_response_links_

T = TypeVar('T', bound='UpdatePolicyResponse')


class UpdatePolicyResponse:
    """Implementation of the 'UpdatePolicyResponse' model.

    Attributes:
        embedded:
            If the `embed` query parameter is set, displays the responses of the related
            resource,
            as defined by the embeddable link specified.
        links:
            URLs to pages related to the resource.
        activation_status:
            The status of the policy.
            Refer to the Policy Activation Status table for a complete list of policy
            statuses.
        created_time:
            The created time of the policy in unix time.
        p_id:
            The Clumio-assigned ID of the policy.
        lock_status:
            The following table describes the possible lock statuses of a policy.

            +----------+-------------------------------------------------------------------+
            |  Status  |                            Description                            |
            +==========+===================================================================+
            | unlocked | Policies are unlocked until an update or deletion task is queued. |
            +----------+-------------------------------------------------------------------+
            | updating | During a policy edit, concurrent edits or deletion requests will  |
            |          | be rejected.                                                      |
            +----------+-------------------------------------------------------------------+
            | deleting | During policy deletion, concurrent edits or deletion requests     |
            |          | will be rejected.                                                 |
            +----------+-------------------------------------------------------------------+
        name:
            The user-provided name of the policy.
        operations:
            A set of service level agreements (SLA) for the policy. A policy can include
            one or more SLA sets that span across various operations.
        organizational_unit_id:
            The Clumio-assigned ID of the organizational unit associated with the policy.
        task_id:
            The Clumio-assigned ID of the task generated by this request.
        timezone:
            The policy-level timezone is deprecated, as the operation-level timezone should
            be used instead.
            The timezone must be a valid location name from the IANA Time Zone database.
            For instance, "America/New_York", "US/Central", "UTC".
            Deprecated: true
        updated_time:
            The updated time of the policy in unix time.
    """

    # Create a mapping from Model property names to API property names
    _names: dict[str, str] = {
        'embedded': '_embedded',
        'links': '_links',
        'activation_status': 'activation_status',
        'created_time': 'created_time',
        'p_id': 'id',
        'lock_status': 'lock_status',
        'name': 'name',
        'operations': 'operations',
        'organizational_unit_id': 'organizational_unit_id',
        'task_id': 'task_id',
        'timezone': 'timezone',
        'updated_time': 'updated_time',
    }

    def __init__(
        self,
        embedded: policy_embedded_.PolicyEmbedded,
        links: update_policy_response_links_.UpdatePolicyResponseLinks,
        activation_status: str,
        created_time: int,
        p_id: str,
        lock_status: str,
        name: str,
        operations: Sequence[policy_operation_.PolicyOperation],
        organizational_unit_id: str,
        task_id: str,
        timezone: str,
        updated_time: int,
    ) -> None:
        """Constructor for the UpdatePolicyResponse class."""

        # Initialize members of the class
        self.embedded: policy_embedded_.PolicyEmbedded = embedded
        self.links: update_policy_response_links_.UpdatePolicyResponseLinks = links
        self.activation_status: str = activation_status
        self.created_time: int = created_time
        self.p_id: str = p_id
        self.lock_status: str = lock_status
        self.name: str = name
        self.operations: Sequence[policy_operation_.PolicyOperation] = operations
        self.organizational_unit_id: str = organizational_unit_id
        self.task_id: str = task_id
        self.timezone: str = timezone
        self.updated_time: int = updated_time

    @classmethod
    def from_dictionary(cls: Type[T], dictionary: Mapping[str, Any]) -> T:
        """Creates an instance of this model from a dictionary

        Args:
            dictionary: A dictionary representation of the object as obtained
                from the deserialization of the server's response. The keys
                MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.
        """

        # Extract variables from the dictionary
        val = dictionary['_embedded']
        val_embedded = policy_embedded_.PolicyEmbedded.from_dictionary(val)

        val = dictionary['_links']
        val_links = update_policy_response_links_.UpdatePolicyResponseLinks.from_dictionary(val)

        val = dictionary['activation_status']
        val_activation_status = val

        val = dictionary['created_time']
        val_created_time = val

        val = dictionary['id']
        val_p_id = val

        val = dictionary['lock_status']
        val_lock_status = val

        val = dictionary['name']
        val_name = val

        val = dictionary['operations']

        val_operations = None
        if val:
            val_operations = list()
            for value in val:
                val_operations.append(policy_operation_.PolicyOperation.from_dictionary(value))

        val = dictionary['organizational_unit_id']
        val_organizational_unit_id = val

        val = dictionary['task_id']
        val_task_id = val

        val = dictionary['timezone']
        val_timezone = val

        val = dictionary['updated_time']
        val_updated_time = val

        # Return an object of this model
        return cls(
            val_embedded,  # type: ignore
            val_links,  # type: ignore
            val_activation_status,  # type: ignore
            val_created_time,  # type: ignore
            val_p_id,  # type: ignore
            val_lock_status,  # type: ignore
            val_name,  # type: ignore
            val_operations,  # type: ignore
            val_organizational_unit_id,  # type: ignore
            val_task_id,  # type: ignore
            val_timezone,  # type: ignore
            val_updated_time,  # type: ignore
        )
